name: CI Phase 2

on:
  push:
    branches:
      - main
      - phase2
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint

      - name: Lint code
        run: pylint app.py

      - name: Build Docker image
        run: |
          docker build -t hivebox:phase2 .

      - name: Run Docker container
        run: |
          docker run -d -p 5000:5000 --name hivebox_container hivebox:phase2

      - name: Run tests
        run: |
          python -m unittest discover tests
