name: Continuous Integration

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo apt-get install -y hadolint

      - name: Lint Dockerfile
        run: hadolint Dockerfile

      - name: Install Python and Pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Lint Python code
        run: pylint app/

      - name: Build Docker image
        run: |
          docker build -t hivebox-app .

      - name: Run tests
        run: |
          docker run hivebox-app python -m unittest discover -s tests

      - name: OpenSSF Scorecard
        uses: ossf/scorecard-action@v2

      - name: Test /version endpoint
        run: |
          curl -f http://localhost:5000/version
